FROM golang:1.15-alpine AS builder
# Set the CWD inside the container
WORKDIR /tmp/ctes
# Set env
ENV GOPROXY https://goproxy.cn
ENV GO111MODULE on
# populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
COPY go.sum .
RUN go mod download
# Copy from project dir to CWD
COPY . .
# Build the Go app from pkg
RUN go build -o ctes SHUCTES/src
# Start fresh from a smaller image
FROM alpine:3.9
RUN apk --no-cache add ca-certificates
#
WORKDIR /app
# Copy app, config, log etc.
COPY --from=builder /tmp/ctes .
COPY --from=builder /tmp/ctes/conf ./conf
COPY --from=builder /tmp/ctes/log ./log
# Container exposes port to the outside world
EXPOSE 8000
# Run the binary program produced by `go install`
#USER app-runner
#RUN pwd
CMD ./ctes

