server:
    Port: :8000
driver:
    Username: root
    Password: 
    Network: tcp
    Server: host.docker.internal
    #Server: localhost
    Port: 3306
    Database: ctes
    InterpolateParams: true
log:
    FilePath: ./log/
    FileName: SHUCTES.log
tag:
    -   课程硬核
    -   过于简单
    -   欢乐
    -   教学新颖
    -   实用好课
    -   内容陈旧
    -   要求明晰
    -   意义不明
    -   自学居多
    -   作业太多
    