package controller

import (
	"SHUCTES/src/config"
	. "SHUCTES/src/database"
	. "SHUCTES/src/log"
	"github.com/gin-gonic/gin"
	"net/http"
)

func GetUserTaggedCourseHandler() gin.HandlerFunc {
	return func(c *gin.Context) {
		username, ok := c.GetQuery("username")
		if !ok {
			c.JSON(http.StatusBadRequest,gin.H{"msg":     "Query wrong"})
			return
		}

		sql := `
SELECT course.uid, course.cid, course.name, course.teachno, course.teachname, tag.tag_idx
FROM ctes.tag, ctes.course
WHERE tag.course_uid = course.uid
AND username = ?; `

		rows, err := DB.Query(sql, username)
		if err != nil {
			Logger.Errorf("While querying: " + err.Error())
			c.JSON(http.StatusInternalServerError,  gin.H{"msg": "server error"})
			return
		}

		type AutoGenerated struct {
			CourseUid	string	`json:"course_uid"`
			CourseCid	string	`json:"course_cid"`
			CourseName	string 	`json:"course"`
			TeachNo    	string `json:"teachno"`
			TeachName	string 	`json:"teachname"`
			TagIdx 		int 	`json:"tag_idx"`
			TagName 	string 	`json:"tag"`
		}
		var jsonSent AutoGenerated
		retSlice :=  make([]AutoGenerated, 0)

		for rows.Next() {
			if err := rows.Scan(&jsonSent.CourseUid, &jsonSent.CourseCid, &jsonSent.CourseName, &jsonSent.TeachNo, &jsonSent.TeachName, &jsonSent.TagIdx); err != nil {
				Logger.Errorf("While scanning rows: " + err.Error())
				c.JSON(http.StatusInternalServerError,  gin.H{"msg": "server error"})
				return
			} else {
				retSlice = append(retSlice, jsonSent)
			}
		}
		rows.Close()

		//为tag添加name string
		for i, t := range retSlice {
			retSlice[i].TagName = config.Conf.TagCon[t.TagIdx - 1]
		}

		c.JSON(http.StatusOK, gin.H{
			"content":	retSlice,
			"length": 	len(retSlice),
			"msg":     "Request successful",
		})
	}
}

func AddCourseTagHandler() gin.HandlerFunc {
	return func(c *gin.Context) {
		username, ok := c.GetQuery("username")
		if !ok {
			c.JSON(http.StatusBadRequest,gin.H{"msg":     "Query wrong"})
			return
		}

		type AutoGenerated struct {
			CourseUid	string	`json:"course_uid"`
			TagIdx 		int 	`json:"tag_idx"`
		}
		var jsonReci AutoGenerated

		if err := c.BindJSON(&jsonReci); err != nil {
			Logger.Errorf("While binding json to struct: " + err.Error())
			c.JSON(http.StatusBadRequest, gin.H{"msg": "Query wrong"})
			return
		} else {
			TagIdxValidation(&jsonReci.TagIdx)
			Logger.Infof("Handling Requset, Username: %s, JsonReci = %#v", username, jsonReci)

			//限制传入TagIdx
			

			sql := `
			INSERT INTO ctes.tag(tag.username, tag.course_uid, tag.tag_idx) 
			SELECT ?, ?, ?;`

			stmt, err := DB.Prepare(sql)
			if err != nil {
				Logger.Errorf("While preparing sql: " + err.Error())
				c.JSON(http.StatusInternalServerError, gin.H{"msg": "server error"})
				return
			}
			res, err := stmt.Exec(username, jsonReci.CourseUid, jsonReci.TagIdx)
			if err != nil {
				Logger.Errorf("While executing sql: " + err.Error())
				c.JSON(http.StatusForbidden, gin.H{"msg": "Duplicate key or other error while querying"})
				return
			}
			lastId, err := res.LastInsertId()
			if err != nil {
				Logger.Errorf("While getting sql result: " + err.Error())
				c.JSON(http.StatusInternalServerError, gin.H{"msg": "server error"})
				return
			}
			rowCnt, err := res.RowsAffected()
			if err != nil {
				Logger.Errorf("While getting sql rowsAffected: " + err.Error())
				c.JSON(http.StatusInternalServerError, gin.H{"msg": "server error"})
				return
			}
			Logger.Infof("Username: %s, JsonReci = %#v, ID = %d, affected = %d\n", username, jsonReci ,lastId, rowCnt)
			c.JSON(http.StatusOK, gin.H{"msg": "request successful"})
		}
	}
}

func DeleteCourseTagHandler() gin.HandlerFunc {
	return func(c *gin.Context) {
		username, ok := c.GetQuery("username")
		if !ok {
			c.JSON(http.StatusBadRequest,gin.H{"msg":     "Query wrong"})
			return
		}

		type AutoGenerated struct {
			CourseUid	string	`json:"course_uid"`
			TagIdx 		int 	`json:"tag_idx"`
		}
		var jsonReci AutoGenerated

		if err := c.BindJSON(&jsonReci); err != nil {
			Logger.Errorf("While binding json to struct: " + err.Error())
			c.JSON(http.StatusBadRequest, gin.H{"msg": "Query wrong"})
			return
		} else {
			TagIdxValidation(&jsonReci.TagIdx)
			Logger.Infof("Handling Requset, Username: %s, JsonReci = %#v", username, jsonReci)

			sql := `
			DELETE FROM ctes.tag
			WHERE tag.username = ?
			AND tag.course_uid = ?
			AND tag.tag_idx = ?;`
			result, err := DB.Exec(sql, username, jsonReci.CourseUid, jsonReci.TagIdx)

			if err != nil{
				Logger.Errorf("While executing sql: " + err.Error())
				c.JSON(http.StatusInternalServerError,  gin.H{"msg": "server error"})
				return
			} else {
				Logger.Infof("Update success, Username: %s, JsonReci = %#v", username, jsonReci)
			}

			rowaffected, err := result.RowsAffected()
			if err != nil {
				Logger.Errorf("Get RowsAffected failed: " + err.Error())
				c.JSON(http.StatusInternalServerError,  gin.H{"msg": "server error"})
			} else {
				Logger.Infof("Affected rows: %d", rowaffected)
				c.JSON(http.StatusOK,  gin.H{"msg": "request successful"})
			}
		}
	}
}

func TagIdxValidation(idx *int) {
	if *idx < 1 {
		*idx = 1
	} else if *idx > 10{
		*idx = 10
	}
}
